"""Seeded random/stochastic disruption scenario generation, for batch
experiments in Stage 7.

`generate_random_scenario` draws every random choice from a single
`random.Random(seed)` instance and only ever picks geometry that exists
on `graph` (a real edge, a real node, a short random walk of real edges,
a small box around a real node's coordinates) — the same determinism and
"always resolvable" guarantees Stage 2's `InstanceBuilder.add_random_stops`
already gives seeded-random stops, applied here to disruptions instead.
"""

from __future__ import annotations

import math
import random

import networkx as nx

from dlm.disruption.schema import Disruption, DisruptionEffect, DisruptionShape, Scenario

_SHAPES = list(DisruptionShape)
_EFFECTS = list(DisruptionEffect)
_METRES_PER_DEGREE_LAT = 111_320.0


def _latlon(graph: nx.MultiDiGraph, node: int) -> tuple[float, float]:
    return (graph.nodes[node]["y"], graph.nodes[node]["x"])


def _random_walk_latlon(
    graph: nx.MultiDiGraph, rng: random.Random, start: int, steps: int
) -> list[tuple[float, float]]:
    """A short walk along `graph`'s real edges from `start`, returned as
    lat/lon waypoints — guarantees the corridor's waypoints trace a real,
    connected route (there is no way to draw a set of random points that
    happen to have no path between them, because the points *are* the
    path)."""
    path = [start]
    current = start
    for _ in range(steps):
        neighbors = list(graph.successors(current))
        if not neighbors:
            break
        current = rng.choice(neighbors)
        path.append(current)
    if len(path) < 2:
        neighbors = list(graph.successors(start)) or list(graph.predecessors(start))
        path.append(rng.choice(neighbors) if neighbors else start)
    return [_latlon(graph, n) for n in path]


def _random_box_around(
    graph: nx.MultiDiGraph, rng: random.Random, center: int
) -> list[tuple[float, float]]:
    """A small (160-500m wide) axis-aligned box around `center`'s real
    coordinates — always contains `center` itself, so the polygon always
    resolves to at least the edges incident to a real node."""
    lat, lon = _latlon(graph, center)
    half_m = rng.uniform(80.0, 250.0)
    dlat = half_m / _METRES_PER_DEGREE_LAT
    dlon = half_m / (_METRES_PER_DEGREE_LAT * math.cos(math.radians(lat)))
    return [
        (lat - dlat, lon - dlon),
        (lat - dlat, lon + dlon),
        (lat + dlat, lon + dlon),
        (lat + dlat, lon - dlon),
    ]


def generate_random_scenario(
    graph: nx.MultiDiGraph,
    seed: int,
    shape: DisruptionShape | None = None,
    effect: DisruptionEffect | None = None,
    name: str | None = None,
) -> Scenario:
    """Generate one seeded-random, single-disruption `Scenario` over
    `graph`'s real nodes/edges.

    Parameters
    ----------
    seed : int
        Every random draw comes from `random.Random(seed)` — the same
        seed against the same graph always produces the identical
        scenario.
    shape, effect : optional
        Fix one or both instead of drawing them randomly (e.g. to build a
        batch that sweeps every shape).
    """
    rng = random.Random(seed)
    chosen_shape = shape or rng.choice(_SHAPES)
    chosen_effect = effect or rng.choice(_EFFECTS)

    kwargs: dict[str, object] = {}
    if chosen_shape is DisruptionShape.EDGE:
        u, v, _k = rng.choice(list(graph.edges(keys=True)))
        kwargs["from_node"] = u
        kwargs["to_node"] = v
    elif chosen_shape is DisruptionShape.NODE:
        kwargs["node"] = rng.choice(list(graph.nodes))
    elif chosen_shape is DisruptionShape.CORRIDOR:
        start = rng.choice(list(graph.nodes))
        kwargs["waypoints"] = _random_walk_latlon(graph, rng, start, steps=rng.randint(2, 4))
    else:
        kwargs["boundary"] = _random_box_around(graph, rng, rng.choice(list(graph.nodes)))

    if chosen_effect is DisruptionEffect.SLOW_ZONE:
        kwargs["speed_factor"] = round(rng.uniform(0.1, 0.7), 2)

    scenario_name = name or f"random_seed_{seed}"
    return Scenario(
        name=scenario_name,
        description=(
            f"Seeded random scenario (seed={seed}): {chosen_shape.value} {chosen_effect.value}."
        ),
        source="Generated by dlm.disruption.generators.generate_random_scenario",
        disruptions=[
            Disruption(id=f"random_{seed}", shape=chosen_shape, effect=chosen_effect, **kwargs)
        ],
    )


def generate_random_scenarios(
    graph: nx.MultiDiGraph, n: int, base_seed: int = 42
) -> list[Scenario]:
    """`n` seeded-random scenarios, seeds `base_seed .. base_seed + n - 1`
    — deterministic given `(n, base_seed)`, for `dlm batch`."""
    return [generate_random_scenario(graph, base_seed + i) for i in range(n)]


__all__ = ["generate_random_scenario", "generate_random_scenarios"]
